from setuptools import setup, find_packages

setup(name='book_task',
      # packages=find_packages(),
      packages=['book_task'],
      include_package_data=True,
      version = "1.0.0",
      license = "proprietary",
      description="Library web app on Flask",
      author='Dmitry Aksenov',
      author_email='aksdmi@gmail.com',
      install_requires=['alembic',
                        'bleach',
                        'blinker',
                        'click',
                        'dominate',
                        'Flask',
                        'Flask-Bootstrap',
                        'Flask-HTTPAuth',
                        'Flask-Login',
                        'Flask-Migrate',
                        'Flask-Moment',
                        'Flask-PageDown',
                        'Flask-SQLAlchemy',
                        'Flask-WTF',
                        'html5lib',
                        'itsdangerous',
                        'Jinja2',
                        'Mako',
                        'Markdown',
                        'MarkupSafe',
                        'python-dateutil',
                        'python-dotenv',
                        'python-editor',
                        'six',
                        'SQLAlchemy',
                        'visitor',
                        'webencodings',
                        'Werkzeug',
                        'WTForms',
                        'coverage',
                        'faker',
                        'httpie',
                        'gunicorn',
                        'psycopg2-binary']
)